name: Releases

on:
  push:
    tags:
      - '*'

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: "Set up JDK 21 from Zulu"
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: "zulu"
      - name: Build with Maven
        run: mvn verify -DskipTests=true -Dmaven.javadoc.skip=true -B -V
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "core/target/configurable-google-java-format-maven-plugin-*.jar"
          bodyFile: "release.md"